version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 5001:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - frontend-volume:/frontend:ro
      - backend-volume:/backend:ro
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-volume:/frontend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - frontend-volume:/backend
volumes:
  frontend-volume:
  backend-volume:
